apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: kong
  labels:
    app: httpbin
    part-of: kong
spec:
  type: NodePort
  selector:
    deploymentconfig: kong-dp
  ports:
    - port: 8080