apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-cp-cm
  namespace: kong
  labels:
    app: kong
    role: control-plane
data:
  KONG_ROLE: "control_plane"
  KONG_DATABASE: "postgres"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
  KONG_CLUSTER_LISTEN: "0.0.0.0:8005"
  KONG_CLUSTER_CERT: "/etc/kong/certs/cluster.crt"
  KONG_CLUSTER_CERT_KEY: "/etc/kong/certs/cluster.key"
