---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-dp-server-blocks
  namespace: kong
data:
  servers.conf: |

    # Health check server
    server {
        server_name kong_health_check;
        listen 0.0.0.0:9001; # can be any other port as well

        access_log off;
        location /health {
          return 200;
        }
    }
